import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import offresRouter from "./offres";
import transactionsRouter from "./transactions";
import statsRouter from "./stats";
import conversationsRouter from "./conversations";
import ratingsRouter from "./ratings";
import profilesRouter from "./profiles";
import adminRouter from "./admin";
import verificationRouter from "./verification";
import notificationsRouter from "./notifications";
import preferencesRouter from "./preferences";
import offerPhotosRouter from "./offer-photos";
import contractsRouter from "./contracts";
import subscriptionsRouter from "./subscriptions";
import paymentSettingsRouter from "./payment-settings";
import adminTeamRouter from "./admin-team";
import devisRouter from "./devis";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import supportRouter from "./support";
import supportTicketsRouter from "./support-tickets";
import devPortalRouter from "./dev-portal";
import favoritesRouter from "./favorites";
import marcheRouter from "./marche";
import usersStatusRouter from "./users-status";
import analyticsRouter from "./analytics";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(offresRouter);
router.use(transactionsRouter);
router.use(statsRouter);
router.use(conversationsRouter);
router.use(ratingsRouter);
router.use(profilesRouter);
router.use(adminRouter);
router.use(verificationRouter);
router.use(notificationsRouter);
router.use(preferencesRouter);
router.use(offerPhotosRouter);
router.use(contractsRouter);
router.use(subscriptionsRouter);
router.use(paymentSettingsRouter);
router.use(adminTeamRouter);
router.use(devisRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(supportTicketsRouter);
router.use(supportRouter);
router.use(devPortalRouter);
router.use(favoritesRouter);
router.use(marcheRouter);
router.use(usersStatusRouter);
router.use(analyticsRouter);

export default router;
